package com.access.productInventoryTracker.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Column;

/**
 * Entity class representing a Product in the inventory system.
 * Maps to the 'product' table in the database using JPA annotations.
 */
@Entity
public class Product {
    
    /** Primary key - auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Product name - required field */
    @Column(nullable = false)
    private String name;

    /** Product price - required field, must be non-negative */
    @Column(nullable = false)
    private double price;

    /** Product category - required field */
    @Column(nullable = false)
    private String category;

    /** Product availability status - required field */
    @Column(nullable = false)
    private boolean available;

    /**
     * Default constructor required by JPA.
     */
    public Product() {

    }

    /**
     * Constructor with all parameters.
     * 
     * @param id the product ID
     * @param name the product name
     * @param price the product price
     * @param category the product category
     * @param available the availability status
     */
    public Product(Long id, String name, double price, String category, boolean available) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.category = category;
        this.available = available;
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public boolean isAvailable() {
        return available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    // toString method for debugging
    @Override
    public String toString() {
        return "Product{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", category='" + category + '\'' +
                ", available=" + available +
                '}';
    }
}
